export const allPps = [
  "/Fotor_AI (1).png",
  "/Fotor_AI (2).png",
  "/Fotor_AI (3).png",
  "/Fotor_AI (4).png",
  "/Fotor_AI (5).png",
  "/Fotor_AI (6).png",
  "/Fotor_AI (7).png",
  "/Fotor_AI (8).png",
  "/Fotor_AI (9).png",
  "/Fotor_AI (10).png",
  "/Fotor_AI (11).png",
  "/Fotor_AI (12).png",
  "/Fotor_AI (13).png",
  "/Fotor_AI (14).png",
  "/Fotor_AI (15).png",
  "/Fotor_AI (16).png",
  "/Fotor_AI (17).png",
  "/Fotor_AI (18).png",
  "/Fotor_AI (19).png",
];